name: Build project
on: 
  push:
    branches:
      - main
jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
          
      - if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1
        
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - uses: actions/upload-artifact@v4
        id: upload-step
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
          
  release_build:
        name: Release Build
        runs-on: ubuntu-latest
        needs: [buildForAllSupportedPlatforms] # Ensures this job runs after the build
        steps:
          - name: List files
            run: ls -R
            
          - name: Zip Build
            run: |
              cd build/StandaloneWindows64
              zip -r ../Build-StandaloneWindows64.zip .
              
          - name: Upload to GitHub Release
            id: release
            uses: softprops/action-gh-release@v1
            with:
              tag_name: latest
              files: Build-StandaloneWindows64.zip
            env:
              GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
            
  send_email:
        name: Send email to ${{ matrix.emails }}
        runs-on: ubuntu-latest
        needs: [release_build] # Ensures this job runs after the build
        strategy:
          fail-fast: false
          matrix:
            emails:
              - lugo.bhz@gmail.com
        steps:
          - name: Send Email with Release Link
            uses: dawidd6/action-send-mail@v3
            with:
              server_address: smtp.gmail.com
              server_port: 587
              username: ${{ secrets.EMAIL_USERNAME }}
              password: ${{ secrets.EMAIL_PASSWORD }}
              subject: "New Build"
              to: ${{ matrix.emails }}
              from: ${{ secrets.EMAIL_USERNAME }}
              body: |
                A new Unity build has been uploaded!
                Download link: ${{ steps.release.outputs.upload_url }}
