name: Build project
on: 
  push:
    branches:
      - main
jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v4
        id: upload-step
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
  send_email:
        name: Send email to ${{ matrix.emails }}
        runs-on: ubuntu-latest
        needs: [buildForAllSupportedPlatforms] # Ensures this job runs after the build
        strategy:
          fail-fast: false
          matrix:
            emails:
              - lugo.bhz@gmail.com
        steps:
          - name: Download Build Artifact
            uses: actions/download-artifact@v4
            id: download-step
            with:
              artifact-ids: ${{ needs.steps.upload-step.outputs.artifact-id }}
              path: ./download
            
          - name: List files
            run: ls -R
            
          - name: Send Email with Build
            uses: dawidd6/action-send-mail@v3
            with:
              server_address: smtp.gmail.com
              server_port: 587
              username: ${{ secrets.EMAIL_USERNAME }}
              password: ${{ secrets.EMAIL_PASSWORD }}
              subject: "New Build"
              to: ${{ matrix.emails }}
              from: ${{ secrets.EMAIL_USERNAME }}
              body: |
                A new build is available for download:
                ${{ needs.steps.upload-step.outputs.artifact-url }}
              attachments: ./download$/Build-${{ needs.buildForAllSupportedPlatforms.strategy.matrix.targetPlatform }}.zip
