name: String Test
on: 
  push:
    branches:
      - main
      
env:
  BUILD_DIR: build/
  FILE_NAME: Build-
  RELEASE_NAME: release-${{ github.sha }} 

jobs:
              
  send_email:
    name: Send email to ${{ matrix.emails }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emails: [lugo.bhz@gmail.com]
        
    steps:
      - name: Initialize strings
        run: |
          echo MY_STRING="" >> $GITHUB_ENV
      - name: Build strings
        run: |
          for platform in StandaloneWindows64
          do
            echo env.MY_STRING = "${{ env.MY_STRING }} \r\n$platform Download link https://github.com/${{ github.repository }}/releases/download/${{ env.RELEASE_NAME }}/${{ env.FILE_NAME }}$platform.zip" >> $GITHUB_ENV
          done
          
      
      - name: Send Email with Release Link
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "New Release"
          to: ${{ matrix.emails }}
          from: ${{ secrets.EMAIL_USERNAME }}
          body: ${{ env.MY_STRING }}
              
      
