name: String Test
on: 
  push:
    branches:
      - main
      
env:
  BUILD_DIR: build/
  FILE_NAME: Build-
  RELEASE_NAME: release-${{ github.sha }} 

jobs:
  generate_email_body:
    name: Generate Email Body
    runs-on: ubuntu-latest
    outputs:
      email-body: ${{ steps.build-string.outputs.email_body }}
    strategy:
      fail-fast: false
      matrix:
        targetPlatform: [StandaloneWindows64]
    steps:
      - name: Build string
        id: build-string
        run: |
            echo BODY = "$BODY \r\n${{ matrix.targetPlatform }} Download link https://github.com/${{ github.repository }}/releases/download/${{ env.RELEASE_NAME }}/${{ env.FILE_NAME }}${{ matrix.targetPlatform }}.zip"
            # Expose BODY as an output
            echo "email_body<<EOF" >> $GITHUB_OUTPUT
            echo -e "$BODY" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
  send_email:
    name: Send email to ${{ matrix.emails }}
    runs-on: ubuntu-latest
    needs: [generate_email_body]
    strategy:
      fail-fast: false
      matrix:
        emails: [lugo.bhz@gmail.com]
        
    steps:
      
      - name: Send Email with Release Link
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "New Release"
          to: ${{ matrix.emails }}
          from: ${{ secrets.EMAIL_USERNAME }}
          body: ${{ needs.generate_email_body.outputs.email_body }}
              
      
